@startuml
[*] --> GameInitializing

state GameInitializing {
  [*] --> CreatingDeck
  CreatingDeck --> CreatingPlayers
  CreatingPlayers --> SettingRoundStarter
  SettingRoundStarter --> WaitingForRoundStart
}

GameInitializing --> RoundStarting : Initialization done

state RoundStarting {
  [*] --> ShufflingDeck
  ShufflingDeck --> DealingCards
}

RoundStarting --> RoundInProgress : Cards dealing done

state RoundInProgress {
  [*] --> PlayerTurn
  PlayerTurn --> SkipTurn : mustSkipTurn
  PlayerTurn --> DrawCards : mustDrawCard
  PlayerTurn --> BotTurn : !mustDrawCard
  PlayerTurn --> HumanTurn : !mustDrawCard

  HumanTurn --> ShowTopCard
  ShowTopCard --> PlayCard

  BotTurn --> PlayCard
  
  PlayCard --> HandleSpecialCard : isSpecial

  HandleSpecialCard --> HandleTwoCards : CardType == TWO
  HandleSpecialCard --> HandleSkipCard : CardType == SKIP
  HandleSpecialCard --> HandleReverseCard : CardType == REVERSE

  SkipTurn --> NextPlayer
  DrawCards --> NextPlayer : Skip turn
  HandleTwoCards --> NextPlayer
  HandleSkipCard --> NextPlayer
  HandleReverseCard --> NextPlayer
  PlayCard --> NextPlayer : !isSpecial

  NextPlayer --> PlayerTurn : !roundOver
}

RoundInProgress --> RoundEnded : Round is over

state RoundEnded {
  [*] --> CalculatingPoints
  CalculatingPoints --> DisplayingResults
  DisplayingResults --> CheckingGameEnd
  CheckingGameEnd --> GameEnded : gameOver
  CheckingGameEnd --> DeterminingNextStarter : !gameOver
  DeterminingNextStarter --> RoundStarting
}

GameEnded --> [*]

@enduml